#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfa.Das.Sas.Web.Views.Provider
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Provider\Detail.cshtml"
    using FeatureToggle.Core.Fluent;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Provider\Detail.cshtml"
    using Sfa.Das.Sas.ApplicationServices.FeatureToggles;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Provider\Detail.cshtml"
    using Sfa.Das.Sas.Resources;
    
    #line default
    #line hidden
    using Sfa.Das.Sas.Web;
    
    #line 1 "..\..\Views\Provider\Detail.cshtml"
    using Sfa.Das.Sas.Web.Extensions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Provider\Detail.cshtml"
    using Sfa.Das.Sas.Web.ViewModels;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Provider/Detail.cshtml")]
    public partial class Detail : System.Web.Mvc.WebViewPage<ApprenticeshipDetailsViewModel>
    {

#line 183 "..\..\Views\Provider\Detail.cshtml"
public System.Web.WebPages.HelperResult ShowTrainingLocation(string title)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 184 "..\..\Views\Provider\Detail.cshtml"
 
if (@Model != null)
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <dt");

WriteLiteralTo(__razor_helper_writer, " class=\"training-location-title\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 187 "..\..\Views\Provider\Detail.cshtml"
          WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\n");


#line 188 "..\..\Views\Provider\Detail.cshtml"

    if (@Model.DeliveryModes.Count == 1 && @Model.DeliveryModes.Contains("100PercentEmployer"))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dd");

WriteLiteralTo(__razor_helper_writer, " id=\"training-location\"");

WriteLiteralTo(__razor_helper_writer, " class=\"training-location\"");

WriteLiteralTo(__razor_helper_writer, ">\n            Training takes place at your location\n        </dd>\n");


#line 194 "..\..\Views\Provider\Detail.cshtml"
    }
    else
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dd");

WriteLiteralTo(__razor_helper_writer, " id=\"training-location\"");

WriteLiteralTo(__razor_helper_writer, " class=\"training-location\"");

WriteLiteralTo(__razor_helper_writer, ">\n");

WriteLiteralTo(__razor_helper_writer, "            ");


#line 198 "..\..\Views\Provider\Detail.cshtml"
WriteTo(__razor_helper_writer, Model.LocationAddressLine);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " \n        </dd>\n");


#line 200 "..\..\Views\Provider\Detail.cshtml"
    }
}


#line default
#line hidden
});

#line 202 "..\..\Views\Provider\Detail.cshtml"
}
#line default
#line hidden

#line 204 "..\..\Views\Provider\Detail.cshtml"
public System.Web.WebPages.HelperResult GetStandardPropertyHtml(string title, string id, string item, bool hideIfEmpty = false)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 205 "..\..\Views\Provider\Detail.cshtml"
 
if (!string.IsNullOrEmpty(item) || !hideIfEmpty)
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <dt");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 9598), Tuple.Create("\"", 9615)

#line 208 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 9606), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 9606), false)
, Tuple.Create(Tuple.Create("", 9609), Tuple.Create("-title", 9609), true)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 208 "..\..\Views\Provider\Detail.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\n");

WriteLiteralTo(__razor_helper_writer, "    <dd");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 9636), Tuple.Create("\"", 9644)

#line 209 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 9641), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 9641), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 9645), Tuple.Create("\"", 9656)

#line 209 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 9653), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 9653), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 209 "..\..\Views\Provider\Detail.cshtml"
WriteTo(__razor_helper_writer, Html.Raw(item));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dd>\n");


#line 210 "..\..\Views\Provider\Detail.cshtml"
}


#line default
#line hidden
});

#line 211 "..\..\Views\Provider\Detail.cshtml"
}
#line default
#line hidden

#line 213 "..\..\Views\Provider\Detail.cshtml"
public System.Web.WebPages.HelperResult GetEmailPropertyHtml(string title, string id, string item, bool hideIfEmpty = false)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 214 "..\..\Views\Provider\Detail.cshtml"
 
if (!string.IsNullOrEmpty(item) || !hideIfEmpty)
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <dt");

WriteLiteralTo(__razor_helper_writer, " class=\"email-title\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 217 "..\..\Views\Provider\Detail.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\n");

WriteLiteralTo(__razor_helper_writer, "    <dd");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 9877), Tuple.Create("\"", 9885)

#line 218 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 9882), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 9882), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"email\"");

WriteLiteralTo(__razor_helper_writer, "><a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 9903), Tuple.Create("\"", 9932)
, Tuple.Create(Tuple.Create("", 9910), Tuple.Create("mailto:", 9910), true)

#line 218 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 9917), Tuple.Create<System.Object, System.Int32>(Html.Raw(item)

#line default
#line hidden
, 9917), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 218 "..\..\Views\Provider\Detail.cshtml"
                                  WriteTo(__razor_helper_writer, Html.Raw(item));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a></dd>\n");


#line 219 "..\..\Views\Provider\Detail.cshtml"
}


#line default
#line hidden
});

#line 220 "..\..\Views\Provider\Detail.cshtml"
}
#line default
#line hidden

#line 222 "..\..\Views\Provider\Detail.cshtml"
public System.Web.WebPages.HelperResult GetStandardPropertyAsLinkHtml(string title, string cssClass, string classTitle, string classIdentifier, string url, string urlTitle = "")
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 223 "..\..\Views\Provider\Detail.cshtml"
 
    if (!string.IsNullOrEmpty(url))
    {
        var linkProtocol = url.StartsWith("http") ? string.Empty : "http://";


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dt");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 10243), Tuple.Create("\"", 10262)

#line 227 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 10251), Tuple.Create<System.Object, System.Int32>(classTitle

#line default
#line hidden
, 10251), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 227 "..\..\Views\Provider\Detail.cshtml"
  WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\n");

WriteLiteralTo(__razor_helper_writer, "        <dd>\n            <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 10303), Tuple.Create("\"", 10327)

#line 229 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 10310), Tuple.Create<System.Object, System.Int32>(linkProtocol

#line default
#line hidden
, 10310), false)

#line 229 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 10323), Tuple.Create<System.Object, System.Int32>(url

#line default
#line hidden
, 10323), false)
);

WriteLiteralTo(__razor_helper_writer, " rel=\"external\"");

WriteLiteralTo(__razor_helper_writer, " target=\"_blank\"");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 10359), Tuple.Create("\"", 10393)

#line 229 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 10367), Tuple.Create<System.Object, System.Int32>(cssClass

#line default
#line hidden
, 10367), false)

#line 229 "..\..\Views\Provider\Detail.cshtml"
      , Tuple.Create(Tuple.Create(" ", 10376), Tuple.Create<System.Object, System.Int32>(classIdentifier

#line default
#line hidden
, 10377), false)
);

WriteLiteralTo(__razor_helper_writer, ">\n");


#line 230 "..\..\Views\Provider\Detail.cshtml"
                

#line default
#line hidden

#line 230 "..\..\Views\Provider\Detail.cshtml"
                 if (string.IsNullOrEmpty(urlTitle))
                {
                    

#line default
#line hidden

#line 232 "..\..\Views\Provider\Detail.cshtml"
WriteTo(__razor_helper_writer, Html.Raw(url));


#line default
#line hidden

#line 232 "..\..\Views\Provider\Detail.cshtml"
                                  
                }
                else
                {
                    

#line default
#line hidden

#line 236 "..\..\Views\Provider\Detail.cshtml"
WriteTo(__razor_helper_writer, Html.Raw(urlTitle));


#line default
#line hidden

#line 236 "..\..\Views\Provider\Detail.cshtml"
                                       
                }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            </a>\n        </dd>\n");


#line 240 "..\..\Views\Provider\Detail.cshtml"
    }


#line default
#line hidden
});

#line 241 "..\..\Views\Provider\Detail.cshtml"
}
#line default
#line hidden

#line 243 "..\..\Views\Provider\Detail.cshtml"
public System.Web.WebPages.HelperResult CreateProgressBar(string message, int progress)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 244 "..\..\Views\Provider\Detail.cshtml"
 
    if (progress > 0)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"progress-container\"");

WriteLiteralTo(__razor_helper_writer, ">\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"progressbar\"");

WriteAttributeTo(__razor_helper_writer, "style", Tuple.Create(" style=\"", 10820), Tuple.Create("\"", 10845)
, Tuple.Create(Tuple.Create("", 10828), Tuple.Create("width:", 10828), true)

#line 248 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create(" ", 10834), Tuple.Create<System.Object, System.Int32>(progress

#line default
#line hidden
, 10835), false)
, Tuple.Create(Tuple.Create("", 10844), Tuple.Create("%", 10844), true)
);

WriteLiteralTo(__razor_helper_writer, "></div>\n        </div>\n");


#line 250 "..\..\Views\Provider\Detail.cshtml"
    }


#line default
#line hidden
});

#line 251 "..\..\Views\Provider\Detail.cshtml"
}
#line default
#line hidden

#line 253 "..\..\Views\Provider\Detail.cshtml"
public System.Web.WebPages.HelperResult GetDeliveryModesHtml(string title, List<string> items, bool hideIfEmpty = false)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 254 "..\..\Views\Provider\Detail.cshtml"
 
if (items != null)
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <dt");

WriteLiteralTo(__razor_helper_writer, " class=\"training-structure\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 257 "..\..\Views\Provider\Detail.cshtml"
     WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\n");

WriteLiteralTo(__razor_helper_writer, "    <dd");

WriteLiteralTo(__razor_helper_writer, " id=\"delivery-modes\"");

WriteLiteralTo(__razor_helper_writer, ">\n        <ul>\n");


#line 260 "..\..\Views\Provider\Detail.cshtml"
            

#line default
#line hidden

#line 260 "..\..\Views\Provider\Detail.cshtml"
             if (items.Exists(m => m.Equals("DayRelease")))
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <li");

WriteLiteralTo(__razor_helper_writer, " class=\"day-release\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 262 "..\..\Views\Provider\Detail.cshtml"
          WriteTo(__razor_helper_writer, Html.Raw("day release"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</li>\n");


#line 263 "..\..\Views\Provider\Detail.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            ");


#line 264 "..\..\Views\Provider\Detail.cshtml"
             if (items.Exists(m => m.Equals("BlockRelease")))
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <li");

WriteLiteralTo(__razor_helper_writer, " class=\"block-release\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 266 "..\..\Views\Provider\Detail.cshtml"
            WriteTo(__razor_helper_writer, Html.Raw("block release"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</li>\n");


#line 267 "..\..\Views\Provider\Detail.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            ");


#line 268 "..\..\Views\Provider\Detail.cshtml"
             if (items.Exists(m => m.Equals("100PercentEmployer")))
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <li");

WriteLiteralTo(__razor_helper_writer, " class=\"hundred-percent-employer\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 270 "..\..\Views\Provider\Detail.cshtml"
                       WriteTo(__razor_helper_writer, Html.Raw("at your location"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</li>\n");


#line 271 "..\..\Views\Provider\Detail.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </ul>\n        <details>\n            <summary>Explain training options</su" +
"mmary>\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"panel panel-border-narrow\"");

WriteLiteralTo(__razor_helper_writer, ">\n                <p>\n                    <span");

WriteLiteralTo(__razor_helper_writer, " class=\"bold-small\"");

WriteLiteralTo(__razor_helper_writer, ">Day release:</span> for example one day a week at the training provider\'s locati" +
"on.\n                </p>\n                <p>\n                    <span");

WriteLiteralTo(__razor_helper_writer, " class=\"bold-small\"");

WriteLiteralTo(__razor_helper_writer, ">Block release:</span> for example 3-4 weeks at the training provider\'s location." +
"\n                </p>\n                <p>\n                    <span");

WriteLiteralTo(__razor_helper_writer, " class=\"bold-small\"");

WriteLiteralTo(__razor_helper_writer, ">At your location:</span> the training provider comes to your workplace.\n        " +
"        </p>\n            </div>\n        </details>\n    </dd>\n");


#line 288 "..\..\Views\Provider\Detail.cshtml"
}


#line default
#line hidden
});

#line 289 "..\..\Views\Provider\Detail.cshtml"
}
#line default
#line hidden

        public Detail()
        {
        }
        public override void Execute()
        {
            
            #line 8 "..\..\Views\Provider\Detail.cshtml"
  
    ViewBag.Title = Model.Name + " - Apprenticeship Provider";
    ViewBag.Description = "The Find Apprenticeship Training service is for employers in England who want to find training courses for their apprentices and search for training providers.";

            
            #line default
            #line hidden
WriteLiteral("\n<main");

WriteLiteral(" id=\"content\"");

WriteLiteral(" class=\"provider-detail\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\n            <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(" id=\"provider-name\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Views\Provider\Detail.cshtml"
           Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\n            </h1>\n        </div>\n    </div>\n    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\n\n            <section>\n\n                <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Training information</h2>\n\n                <dl");

WriteLiteral(" class=\"data-list--provider data-list--compact\"");

WriteLiteral(">\n                    <dt>Apprenticeship: </dt>\n                    <dd>");

            
            #line 29 "..\..\Views\Provider\Detail.cshtml"
                   Write(Model.ApprenticeshipName);

            
            #line default
            #line hidden
WriteLiteral("</dd>\n                    <dt>Level: </dt>\n                    <dd>");

            
            #line 31 "..\..\Views\Provider\Detail.cshtml"
                   Write(Model.ApprenticeshipLevel);

            
            #line default
            #line hidden
WriteLiteral(" (equivalent to ");

            
            #line 31 "..\..\Views\Provider\Detail.cshtml"
                                                             Write(EquivalenceLevelService.GetApprenticeshipLevel(Model.ApprenticeshipLevel));

            
            #line default
            #line hidden
WriteLiteral(")</dd>\n\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Views\Provider\Detail.cshtml"
               Write(GetDeliveryModesHtml("Training options:", Model.DeliveryModes));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Views\Provider\Detail.cshtml"
               Write(ShowTrainingLocation("Training location:"));

            
            #line default
            #line hidden
WriteLiteral("\n\n                    <dt>Achievement rates: </dt>\n                    <dd>\n     " +
"                   <div");

WriteLiteral(" class=\"rating\"");

WriteLiteral(">\n                            <span");

WriteLiteral(" class=\"national-rate\"");

WriteLiteral(">\n");

WriteLiteral("                                ");

            
            #line 40 "..\..\Views\Provider\Detail.cshtml"
                           Write(Model.AchievementRateMessage);

            
            #line default
            #line hidden
WriteLiteral("\n                            </span>\n");

            
            #line 42 "..\..\Views\Provider\Detail.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Provider\Detail.cshtml"
                             if (Model.AchievementRateMessage != "no data available")
                            {
                                
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Provider\Detail.cshtml"
                           Write(CreateProgressBar(Model.AchievementRateMessage, Model.AchievementRate));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Provider\Detail.cshtml"
                                                                                                       
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\n\n");

            
            #line 48 "..\..\Views\Provider\Detail.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Provider\Detail.cshtml"
                         if (Model.AchievementRateMessage != "no data available")
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"rating national-achievement-bar\"");

WriteLiteral(">\n                                <b");

WriteLiteral(" class=\"font-small\"");

WriteLiteral(">National average:</b>\n                                <span");

WriteLiteral(" class=\"national-rate\"");

WriteLiteral(">\n");

WriteLiteral("                                    ");

            
            #line 53 "..\..\Views\Provider\Detail.cshtml"
                               Write(Model.NationalAchievementRateMessage);

            
            #line default
            #line hidden
WriteLiteral("\n                                </span>\n");

WriteLiteral("                                ");

            
            #line 55 "..\..\Views\Provider\Detail.cshtml"
                           Write(CreateProgressBar(Model.NationalAchievementRateMessage, Model.NationalAchievementRate));

            
            #line default
            #line hidden
WriteLiteral("\n                            </div>\n");

            
            #line 57 "..\..\Views\Provider\Detail.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 58 "..\..\Views\Provider\Detail.cshtml"
                         if (Model.AchievementRateMessage != "no data available")
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <details");

WriteLiteral(" class=\"more-information\"");

WriteLiteral(">\n                                <summary>Explain achievement rate</summary>\n   " +
"                             <div");

WriteLiteral(" class=\"panel panel-border-narrow\"");

WriteLiteral(">\n                                    <p>Percentage of apprentices who successful" +
"ly achieved a similar apprenticeship with this training provider.</p>\n          " +
"                          <p>Based on the latest data for ");

            
            #line 64 "..\..\Views\Provider\Detail.cshtml"
                                                               Write(Model.OverallCohort);

            
            #line default
            #line hidden
WriteLiteral(" apprentices.</p>\n                                    <p");

WriteLiteral(" class=\"font-small\"");

WriteLiteral(">Source: <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3198), Tuple.Create("\"", 3236)
            
            #line 65 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 3205), Tuple.Create<System.Object, System.Int32>(Model.AchievementRateSourceUrl
            
            #line default
            #line hidden
, 3205), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" rel=\"external\"");

WriteLiteral(">Skills Funding Agency apprenticeship achievement rates</a></p>\n                 " +
"               </div>\n                            </details>\n");

            
            #line 68 "..\..\Views\Provider\Detail.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </dd>\n                </dl>\n\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">About the apprenticeship: </h3>\n");

WriteLiteral("                ");

            
            #line 73 "..\..\Views\Provider\Detail.cshtml"
           Write(Html.MarkdownToHtml(Model.Apprenticeship.ApprenticeshipMarketingInfo));

            
            #line default
            #line hidden
WriteLiteral("\n\n            </section>\n            <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Provider information</h2>\n        </div>\n        <div");

WriteLiteral(" class=\"column-one-third\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"panel--contact\"");

WriteLiteral(">\n                <h2");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Contact details</h2>\n                <dl>\n");

WriteLiteral("                    ");

            
            #line 82 "..\..\Views\Provider\Detail.cshtml"
               Write(GetStandardPropertyAsLinkHtml("Website:", "course-link", "apprenticeshipContactTitle", "apprenticeshipContact", Model.Apprenticeship.ApprenticeshipInfoUrl, "training provider website"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                    ");

            
            #line 83 "..\..\Views\Provider\Detail.cshtml"
               Write(GetStandardPropertyHtml("Phone number:", "phone", Model.ContactInformation.Phone));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                    ");

            
            #line 84 "..\..\Views\Provider\Detail.cshtml"
               Write(GetEmailPropertyHtml("Email:", "email", Model.ContactInformation.Email));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                    ");

            
            #line 85 "..\..\Views\Provider\Detail.cshtml"
               Write(GetStandardPropertyAsLinkHtml("Contact page:", "contact-link", "providerContactTitle", "providerContact", Model.ContactInformation.ContactUsUrl, "contact this training provider"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                    ");

            
            #line 86 "..\..\Views\Provider\Detail.cshtml"
               Write(ShowTrainingLocation("Address:"));

            
            #line default
            #line hidden
WriteLiteral("\n                </dl>\n            </div>\n        </div>\n    </div>\n    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\n            <section>\n                \n                <div");

WriteLiteral(" class=\"provider-marketing-info\"");

WriteLiteral(">\n");

WriteLiteral("                    ");

            
            #line 96 "..\..\Views\Provider\Detail.cshtml"
               Write(Html.MarkdownToHtml(Model.ProviderMarketingInfo));

            
            #line default
            #line hidden
WriteLiteral("\n                </div>\n                <dl");

WriteLiteral(" class=\"data-list--provider data-list--compact\"");

WriteLiteral(">\n                    <dt>Employer satisfaction:</dt>\n                    <dd>\n  " +
"                      <div");

WriteLiteral(" class=\"rating rating--inline\"");

WriteLiteral(">\n                            <span");

WriteLiteral(" id=\"employer-satisfaction\"");

WriteAttribute("class", Tuple.Create(" class=\"", 5156), Tuple.Create("\"", 5198)
, Tuple.Create(Tuple.Create("", 5164), Tuple.Create("rating-", 5164), true)
            
            #line 102 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 5171), Tuple.Create<System.Object, System.Int32>(Model.EmployerSatisfaction
            
            #line default
            #line hidden
, 5171), false)
);

WriteLiteral(">\n");

WriteLiteral("                                ");

            
            #line 103 "..\..\Views\Provider\Detail.cshtml"
                           Write(Model.EmployerSatisfactionMessage);

            
            #line default
            #line hidden
WriteLiteral("\n                            </span>\n");

WriteLiteral("                            ");

            
            #line 105 "..\..\Views\Provider\Detail.cshtml"
                       Write(CreateProgressBar(Model.EmployerSatisfactionMessage, (int)Model.EmployerSatisfaction));

            
            #line default
            #line hidden
WriteLiteral("\n                        </div>\n                    </dd>\n                    <dt" +
">Learner satisfaction:</dt>\n                    <dd>\n                        <di" +
"v");

WriteLiteral(" class=\"rating rating--inline\"");

WriteLiteral(">\n                            <span");

WriteLiteral(" id=\"learner-satisfaction\"");

WriteAttribute("class", Tuple.Create(" class=\"", 5671), Tuple.Create("\"", 5712)
, Tuple.Create(Tuple.Create("", 5679), Tuple.Create("rating-", 5679), true)
            
            #line 111 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 5686), Tuple.Create<System.Object, System.Int32>(Model.LearnerSatisfaction
            
            #line default
            #line hidden
, 5686), false)
);

WriteLiteral(">\n");

WriteLiteral("                                ");

            
            #line 112 "..\..\Views\Provider\Detail.cshtml"
                           Write(Model.LearnerSatisfactionMessage);

            
            #line default
            #line hidden
WriteLiteral("\n                            </span>\n");

WriteLiteral("                            ");

            
            #line 114 "..\..\Views\Provider\Detail.cshtml"
                       Write(CreateProgressBar(Model.LearnerSatisfactionMessage, (int) Model.LearnerSatisfaction));

            
            #line default
            #line hidden
WriteLiteral("\n                        </div>\n                    </dd>\n");

            
            #line 117 "..\..\Views\Provider\Detail.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\Provider\Detail.cshtml"
                     if (!(Model.EmployerSatisfactionMessage == "no data available" && Model.LearnerSatisfactionMessage == "no data available"))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p");

WriteLiteral(" class=\"satisfaction-source font-small\"");

WriteLiteral(">\n                            Source: <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6260), Tuple.Create("\"", 6295)
            
            #line 120 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 6267), Tuple.Create<System.Object, System.Int32>(Model.SatisfactionSourceUrl
            
            #line default
            #line hidden
, 6267), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Skills Funding Agency FE Choices</a>\n                        </p>\n");

            
            #line 122 "..\..\Views\Provider\Detail.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 123 "..\..\Views\Provider\Detail.cshtml"
               Write(GetStandardPropertyHtml("Legal trading name:", "legal-name", Model.LegalName));

            
            #line default
            #line hidden
WriteLiteral("\n                </dl>\n                \n\n");

            
            #line 127 "..\..\Views\Provider\Detail.cshtml"
                
            
            #line default
            #line hidden
            
            #line 127 "..\..\Views\Provider\Detail.cshtml"
                 if (Is<NationalProvidersFeature>.Enabled && Model.NationalProvider)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p");

WriteLiteral(" class=\"national-message\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" class=\"tag tag-new\"");

WriteLiteral(">National</span> This training provider is willing to offer apprenticeship traini" +
"ng across England.\n                    </p>\n");

            
            #line 132 "..\..\Views\Provider\Detail.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 134 "..\..\Views\Provider\Detail.cshtml"
                
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\Provider\Detail.cshtml"
                 if (Is<FatLevyJourneyFeature>.Enabled)
                {
                    if (Model.IsLevyPayingEmployer.HasValue && Model.IsLevyPayingEmployer.Value && Model.HasNonLevyContract == false)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p");

WriteLiteral(" class=\"detail-highlight\"");

WriteLiteral(">\n                            Only levy paying employers can work with this provi" +
"der\n                        </p>\n");

            
            #line 141 "..\..\Views\Provider\Detail.cshtml"
                    }

                    if (Model.HasParentCompanyGuarantee)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p");

WriteLiteral(" class=\"detail-highlight\"");

WriteLiteral(">\n                            Provider is supported by a parent company guarantee" +
"\n                        </p>\n");

            
            #line 148 "..\..\Views\Provider\Detail.cshtml"
                    }

                    if (Model.IsNewProvider)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p");

WriteLiteral(" class=\"detail-highlight\"");

WriteLiteral(">\n                            New organisation with no financial track record\n   " +
"                     </p>\n");

            
            #line 155 "..\..\Views\Provider\Detail.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                <p>\n                    <em>Content maintained by ");

            
            #line 158 "..\..\Views\Provider\Detail.cshtml"
                                         Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</em>\n                </p>\n            </section>\n            <div");

WriteLiteral(" class=\"survey-panel\"");

WriteLiteral(">\n                <h2");

WriteLiteral(" class=\"bold-large\"");

WriteLiteral(@">
                    Give us your feedback
                </h2>
                <p>
                    This is a new service and your feedback will help us improve it.<br />
                    Use the link below to take part in a short survey.
                </p>
                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8323), Tuple.Create("\"", 8346)
            
            #line 169 "..\..\Views\Provider\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 8330), Tuple.Create<System.Object, System.Int32>(Model.SurveyUrl
            
            #line default
            #line hidden
, 8330), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"button\"");

WriteLiteral(">Take the survey</a>\n            </div>\n            <aside");

WriteLiteral(" class=\"disclaimer\"");

WriteLiteral(">\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(@">Content disclaimer</h3>
                <p>
                    Skills Funding Agency cannot guarantee the accuracy of course information on this site and makes no representations about the quality of any courses which appear on the site. Skills Funding Agency is not liable for any losses suffered as a result of any party relying on the course information provided.
                </p>
            </aside>
        </div>
    </div>
</main>



");

WriteLiteral("\n");

WriteLiteral("\n");

WriteLiteral("\n");

WriteLiteral("\n");

WriteLiteral("\n");

        }
    }
}
#pragma warning restore 1591
