#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfa.Das.Sas.Web.Views.Start
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Sfa.Das.Sas.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Start/Start.cshtml")]
    public partial class Start : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Start()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Start\Start.cshtml"
  
    ViewBag.Title = "Find Apprenticeship Training | Skills Funding Agency";
    ViewBag.Description = "The Find Apprenticeship Training service is for employers in England who want to find training courses for their apprentices and search for training providers.";

            
            #line default
            #line hidden
WriteLiteral("\n<main");

WriteLiteral(" id=\"content\"");

WriteLiteral(" role=\"main\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\n            <hgroup>\n                <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">\n                    Find apprenticeship training\n                </h1>\n        " +
"    </hgroup>\n            <p>For employers looking to take on apprentices.</p>\n\n" +
"            <p>Use this service to:</p>\r\n\r\n            <ul");

WriteLiteral(" class=\"list list-bullet\"");

WriteLiteral(">\r\n                <li>search for apprenticeship training by job role or keyword<" +
"/li>\r\n                <li>find training providers who offer the apprenticeship t" +
"raining you choose</li>\r\n            </ul>\r\n            \r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\Start\Start.cshtml"
       Write(Html.ActionLink("Start", "Search", "Apprenticeship", null, new { id = "start-button", @class = "button margin-top-x2 button-start" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Views\Start\Start.cshtml"
       Write(Html.Partial("_Help"));

            
            #line default
            #line hidden
WriteLiteral("\n\n        </div>\n    </div>\n</main>");

        }
    }
}
#pragma warning restore 1591
