#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfa.Das.Sas.Web.Views.Apprenticeship
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Apprenticeship\Framework.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Apprenticeship\Framework.cshtml"
    using Sfa.Das.Sas.Resources;
    
    #line default
    #line hidden
    using Sfa.Das.Sas.Web;
    
    #line 3 "..\..\Views\Apprenticeship\Framework.cshtml"
    using Sfa.Das.Sas.Web.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Apprenticeship/Framework.cshtml")]
    public partial class Framework : System.Web.Mvc.WebViewPage<Sfa.Das.Sas.Web.ViewModels.FrameworkViewModel>
    {

#line 187 "..\..\Views\Apprenticeship\Framework.cshtml"
public System.Web.WebPages.HelperResult GetStandardProperty(string title, string id, string item, bool hideIfEmpty = false)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 188 "..\..\Views\Apprenticeship\Framework.cshtml"
 
if (!string.IsNullOrEmpty(item) || !hideIfEmpty)
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dt>");


#line 191 "..\..\Views\Apprenticeship\Framework.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\n");

WriteLiteralTo(__razor_helper_writer, "        <dd");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 8490), Tuple.Create("\"", 8498)

#line 192 "..\..\Views\Apprenticeship\Framework.cshtml"
, Tuple.Create(Tuple.Create("", 8495), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 8495), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 192 "..\..\Views\Apprenticeship\Framework.cshtml"
WriteTo(__razor_helper_writer, Html.MarkdownToHtml(item));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dd>\n");


#line 193 "..\..\Views\Apprenticeship\Framework.cshtml"
}


#line default
#line hidden
});

#line 194 "..\..\Views\Apprenticeship\Framework.cshtml"
}
#line default
#line hidden

#line 196 "..\..\Views\Apprenticeship\Framework.cshtml"
public System.Web.WebPages.HelperResult GetFundingBandProperty(int value)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 197 "..\..\Views\Apprenticeship\Framework.cshtml"
 
var fundingCapFormatted = value.ToString("C0", CultureInfo.CurrentCulture);



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <dt>Funding cap<br />(from 1 May 2017)</dt>\n");

WriteLiteralTo(__razor_helper_writer, "    <dd");

WriteLiteralTo(__razor_helper_writer, " id=\"funding-cap\"");

WriteLiteralTo(__razor_helper_writer, ">\n        Up to ");


#line 202 "..\..\Views\Apprenticeship\Framework.cshtml"
WriteTo(__razor_helper_writer, fundingCapFormatted);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " per apprentice.<br />\n        <a");

WriteLiteralTo(__razor_helper_writer, " href=\"https://www.gov.uk/government/publications/apprenticeship-levy-how-it-will" +
"-work/apprenticeship-levy-how-it-will-work#buying-apprenticeship-training-and-as" +
"sessment\"");

WriteLiteralTo(__razor_helper_writer, " target=\"_blank\"");

WriteLiteralTo(__razor_helper_writer, ">More information about funding</a>\n    </dd>\n");


#line 205 "..\..\Views\Apprenticeship\Framework.cshtml"


#line default
#line hidden
});

#line 205 "..\..\Views\Apprenticeship\Framework.cshtml"
}
#line default
#line hidden

        public Framework()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Apprenticeship\Framework.cshtml"
  
    ViewBag.Title = @Model.Title + " - Apprenticeship Framework";
    ViewBag.Description = "The Find Apprenticeship Training service is for employers in England who want to find training courses for their apprentices and search for training providers.";

            
            #line default
            #line hidden
WriteLiteral("\n\n<main");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\n            <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 15 "..\..\Views\Apprenticeship\Framework.cshtml"
           Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\n            </h1>\n            <p>\n                This information is taken from" +
" an apprenticeship framework. It sets out what qualifications the apprentice can" +
" achieve.\n            </p>\n");

            
            #line 20 "..\..\Views\Apprenticeship\Framework.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Apprenticeship\Framework.cshtml"
             if (Model.ExpiryDateString != null)
            {


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"notice\"");

WriteLiteral(">\n                    <i");

WriteLiteral(" class=\"icon icon-important\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" class=\"visuallyhidden\"");

WriteLiteral(">Warning</span>\n                    </i>\n                    <strong");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">\n                        This apprenticeship is closed to new starters from ");

            
            #line 28 "..\..\Views\Apprenticeship\Framework.cshtml"
                                                                      Write(Model.ExpiryDateString);

            
            #line default
            #line hidden
WriteLiteral("\n                    </strong>\n                </div>\n");

            
            #line 31 "..\..\Views\Apprenticeship\Framework.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\n\n        <div");

WriteLiteral(" class=\"column-third\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"related-container\"");

WriteLiteral(">\n                <aside");

WriteLiteral(" class=\"hidden-for-mobile-tablet\"");

WriteLiteral(">\n\n                    <a");

WriteLiteral(" class=\"button ui-find-training-providers\"");

WriteLiteral(" rel=\"nofollow\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1442), Tuple.Create("\"", 1577)
            
            #line 39 "..\..\Views\Apprenticeship\Framework.cshtml"
      , Tuple.Create(Tuple.Create("", 1449), Tuple.Create<System.Object, System.Int32>(Url.Action("SearchForFrameworkProviders", "Apprenticeship", new {frameworkId = Model.FrameworkId, keywords = Model.SearchTerm})
            
            #line default
            #line hidden
, 1449), false)
);

WriteLiteral(">\n                        Find training providers\n                    </a>\n      " +
"          </aside>\n            </div>\n\n        </div>\n    </div>\n\n    <section>\n" +
"        <header>\n            <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">\n                Summary of this apprenticeship framework\n            </h2>\n    " +
"    </header>\n\n        <dl");

WriteLiteral(" class=\"data-list\"");

WriteLiteral(">\n");

            
            #line 56 "..\..\Views\Apprenticeship\Framework.cshtml"
            
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Apprenticeship\Framework.cshtml"
             if (!string.IsNullOrEmpty(Model.FrameworkOverview))
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt");

WriteLiteral(" class=\"overviewTitle\"");

WriteLiteral(">Overview of role</dt>\n");

WriteLiteral("                <dd");

WriteLiteral(" class=\"overviewText\"");

WriteLiteral(">");

            
            #line 59 "..\..\Views\Apprenticeship\Framework.cshtml"
                                    Write(Model.FrameworkOverview);

            
            #line default
            #line hidden
WriteLiteral(" </dd>\n");

            
            #line 60 "..\..\Views\Apprenticeship\Framework.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            \n");

WriteLiteral("            ");

            
            #line 62 "..\..\Views\Apprenticeship\Framework.cshtml"
       Write(GetStandardProperty("Level", "level", $"{Model.Level} (equivalent to {@EquivalenveLevelService.GetApprenticeshipLevel(Model.Level.ToString())})"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("            ");

            
            #line 63 "..\..\Views\Apprenticeship\Framework.cshtml"
       Write(GetFundingBandProperty(Model.MaxFunding));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("            ");

            
            #line 64 "..\..\Views\Apprenticeship\Framework.cshtml"
       Write(GetStandardProperty("Typical length", "length", Model.TypicalLengthMessage));

            
            #line default
            #line hidden
WriteLiteral("\n            <dt>Entry requirements</dt>\n            <dd");

WriteLiteral(" class=\"entry-requirements\"");

WriteLiteral(">\n");

            
            #line 67 "..\..\Views\Apprenticeship\Framework.cshtml"
                
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Apprenticeship\Framework.cshtml"
                 if (!string.IsNullOrEmpty(Model.EntryRequirements))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div>");

            
            #line 69 "..\..\Views\Apprenticeship\Framework.cshtml"
                    Write(Model.EntryRequirements);

            
            #line default
            #line hidden
WriteLiteral("</div>\n");

            
            #line 70 "..\..\Views\Apprenticeship\Framework.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div>Your chosen training provider can advise you about entry req" +
"uirements for apprentices.</div>\n            </dd>\n\n            <dt>Suitable rol" +
"es for apprentices</dt>\n            <dd");

WriteLiteral(" class=\"job-roles\"");

WriteLiteral(">\n");

            
            #line 76 "..\..\Views\Apprenticeship\Framework.cshtml"
                
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Apprenticeship\Framework.cshtml"
                 if (Model.JobRoles != null && Model.JobRoles.Any())
                {

            
            #line default
            #line hidden
WriteLiteral("                    <ul>\n");

            
            #line 79 "..\..\Views\Apprenticeship\Framework.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Apprenticeship\Framework.cshtml"
                         foreach (var jobRole in Model.JobRoles.Take(5))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>");

            
            #line 81 "..\..\Views\Apprenticeship\Framework.cshtml"
                           Write(jobRole);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 82 "..\..\Views\Apprenticeship\Framework.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 83 "..\..\Views\Apprenticeship\Framework.cshtml"
                         if (Model.JobRoles.Count() > 5)
                        {
                            foreach (var jobRole in Model.JobRoles.Skip(5))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li");

WriteLiteral(" class=\"default-hidden\"");

WriteLiteral(">");

            
            #line 87 "..\..\Views\Apprenticeship\Framework.cshtml"
                                                      Write(jobRole);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 88 "..\..\Views\Apprenticeship\Framework.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"showmore hidden\"");

WriteLiteral(">Show more</a>\n");

            
            #line 90 "..\..\Views\Apprenticeship\Framework.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\n");

            
            #line 92 "..\..\Views\Apprenticeship\Framework.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\n                <div>\n                    Your chosen training provider can advi" +
"se you about the kinds of skills apprentices will learn.\n                </div>\n" +
"            </dd>\n            <dt>Qualifications</dt>\n            <dd>\n         " +
"       <div");

WriteLiteral(" class=\"qualifications\"");

WriteLiteral(">\n");

            
            #line 101 "..\..\Views\Apprenticeship\Framework.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Apprenticeship\Framework.cshtml"
                     if (Model.CompetencyQualification != null && Model.CompetencyQualification.Any())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"competencyQualifications\"");

WriteLiteral(">\n                            <p>Apprentices will achieve a practical (or \'compet" +
"ence\') qualification:</p>\n                            <ul>\n");

            
            #line 106 "..\..\Views\Apprenticeship\Framework.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 106 "..\..\Views\Apprenticeship\Framework.cshtml"
                                 foreach (var qualification in Model.CompetencyQualification.Take(3))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 108 "..\..\Views\Apprenticeship\Framework.cshtml"
                                   Write(qualification);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 109 "..\..\Views\Apprenticeship\Framework.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 111 "..\..\Views\Apprenticeship\Framework.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\Apprenticeship\Framework.cshtml"
                                 if (Model.CompetencyQualification.Count() > 3)
                                {
                                    foreach (var qualification in Model.CompetencyQualification.Skip(3))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" class=\"default-hidden\"");

WriteLiteral(">");

            
            #line 115 "..\..\Views\Apprenticeship\Framework.cshtml"
                                                              Write(qualification);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 116 "..\..\Views\Apprenticeship\Framework.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"showmore hidden\"");

WriteLiteral(">Show more</a>\n");

            
            #line 118 "..\..\Views\Apprenticeship\Framework.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\n                        </div>\n");

            
            #line 121 "..\..\Views\Apprenticeship\Framework.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 123 "..\..\Views\Apprenticeship\Framework.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Apprenticeship\Framework.cshtml"
                     if (Model.KnowledgeQualification != null && Model.KnowledgeQualification.Any())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"knowledgeQualifications\"");

WriteLiteral(">\n                            <p>Apprentices will also achieve a theory-based (or" +
" \'knowledge\') qualification:</p>\n                            <ul>\n");

            
            #line 128 "..\..\Views\Apprenticeship\Framework.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 128 "..\..\Views\Apprenticeship\Framework.cshtml"
                                 foreach (var qualification in Model.KnowledgeQualification.Take(3))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 130 "..\..\Views\Apprenticeship\Framework.cshtml"
                                   Write(qualification);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 131 "..\..\Views\Apprenticeship\Framework.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 133 "..\..\Views\Apprenticeship\Framework.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 133 "..\..\Views\Apprenticeship\Framework.cshtml"
                                 if (Model.KnowledgeQualification.Count() > 3)
                                {
                                    foreach (var qualification in Model.KnowledgeQualification.Skip(3))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" class=\"default-hidden\"");

WriteLiteral(">");

            
            #line 137 "..\..\Views\Apprenticeship\Framework.cshtml"
                                                              Write(qualification);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 138 "..\..\Views\Apprenticeship\Framework.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"showmore hidden\"");

WriteLiteral(">Show more</a>\n");

            
            #line 140 "..\..\Views\Apprenticeship\Framework.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\n                        </div>\n");

            
            #line 143 "..\..\Views\Apprenticeship\Framework.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 145 "..\..\Views\Apprenticeship\Framework.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 145 "..\..\Views\Apprenticeship\Framework.cshtml"
                     if (Model.CombinedQualificiation != null && Model.CombinedQualificiation.Any())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"combinedQualification\"");

WriteLiteral(">\n                            <p>Apprentices will achieve a practical and theory-" +
"based (or \'combined\') qualification:</p>\n                            <ul>\n");

            
            #line 150 "..\..\Views\Apprenticeship\Framework.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 150 "..\..\Views\Apprenticeship\Framework.cshtml"
                                 foreach (var qualification in Model.CombinedQualificiation.Take(3))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 152 "..\..\Views\Apprenticeship\Framework.cshtml"
                                   Write(qualification);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 153 "..\..\Views\Apprenticeship\Framework.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 155 "..\..\Views\Apprenticeship\Framework.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 155 "..\..\Views\Apprenticeship\Framework.cshtml"
                                 if (Model.CombinedQualificiation.Count() > 3)
                                {
                                    foreach (var qualification in Model.CombinedQualificiation.Skip(3))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" class=\"default-hidden\"");

WriteLiteral(">");

            
            #line 159 "..\..\Views\Apprenticeship\Framework.cshtml"
                                                              Write(qualification);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");

            
            #line 160 "..\..\Views\Apprenticeship\Framework.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"showmore hidden\"");

WriteLiteral(">Show more</a>\n");

            
            #line 162 "..\..\Views\Apprenticeship\Framework.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\n                        </div>\n");

            
            #line 165 "..\..\Views\Apprenticeship\Framework.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\n\n");

            
            #line 168 "..\..\Views\Apprenticeship\Framework.cshtml"
                
            
            #line default
            #line hidden
            
            #line 168 "..\..\Views\Apprenticeship\Framework.cshtml"
                 if (Model.CompletionQualifications != string.Empty)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p");

WriteLiteral(" class=\"completionQualifications\"");

WriteLiteral(">");

            
            #line 170 "..\..\Views\Apprenticeship\Framework.cshtml"
                                                   Write(Model.CompletionQualifications);

            
            #line default
            #line hidden
WriteLiteral("</p>\n");

            
            #line 171 "..\..\Views\Apprenticeship\Framework.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <p");

WriteLiteral(" class=\"qualificationsStatic\"");

WriteLiteral(">Your chosen training provider can advise you about the qualifications open to ap" +
"prentices as they can change depending on individual and other circumstances.</p" +
">\n            </dd>\n\n            <dt>Professional registration</dt>\n            " +
"<dd>");

            
            #line 176 "..\..\Views\Apprenticeship\Framework.cshtml"
           Write(Model.ProfessionalRegistration);

            
            #line default
            #line hidden
WriteLiteral("</dd>\n        </dl>\n\n        <div");

WriteLiteral(" id=\"bottom-actions\"");

WriteLiteral(">\n            <a");

WriteLiteral(" class=\"button ui-find-training-providers\"");

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(" id=\"ga-find-provider-bottom\"");

WriteAttribute("href", Tuple.Create(" href=\"", 8076), Tuple.Create("\"", 8211)
            
            #line 180 "..\..\Views\Apprenticeship\Framework.cshtml"
                           , Tuple.Create(Tuple.Create("", 8083), Tuple.Create<System.Object, System.Int32>(Url.Action("SearchForFrameworkProviders", "Apprenticeship", new {frameworkId = Model.FrameworkId, keywords = Model.SearchTerm})
            
            #line default
            #line hidden
, 8083), false)
);

WriteLiteral(">\n                Find training providers\n            </a>\n        </div>\n    </s" +
"ection>\n</main>\n\n");

WriteLiteral("\n");

        }
    }
}
#pragma warning restore 1591
