#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfa.Das.Sas.Web.Views.Apprenticeship
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Sfa.Das.Sas.Web;
    
    #line 1 "..\..\Views\Apprenticeship\SearchResults.cshtml"
    using Sfa.Das.Sas.Web.ViewModels;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Apprenticeship/SearchResults.cshtml")]
    public partial class SearchResults : System.Web.Mvc.WebViewPage<ApprenticeshipSearchResultViewModel>
    {

#line 71 "..\..\Views\Apprenticeship\SearchResults.cshtml"
public System.Web.WebPages.HelperResult GetPaginationBackLink()
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 72 "..\..\Views\Apprenticeship\SearchResults.cshtml"
 
    if (Model.ActualPage > 1)
    {
        var previousPage = @Model.ActualPage - 1;
        var title = $"Previous page {@previousPage} of {@Model.LastPage}";
        var url = @Url.Action("SearchResults", "Apprenticeship", GetNavigationRouteValues(Model.SearchTerm, @previousPage, Model.AggregationLevel), null);
            

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "<a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 2506), Tuple.Create("\"", 2517)

#line 78 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 2513), Tuple.Create<System.Object, System.Int32>(url

#line default
#line hidden
, 2513), false)
);

WriteLiteralTo(__razor_helper_writer, " style=\"visibility: visible\"");

WriteLiteralTo(__razor_helper_writer, " class=\"page-navigation__btn prev\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <i");

WriteLiteralTo(__razor_helper_writer, " class=\"arrow-button fa fa-angle-left\"");

WriteLiteralTo(__razor_helper_writer, "></i>\r\n                <span");

WriteLiteralTo(__razor_helper_writer, " class=\"description\"");

WriteLiteralTo(__razor_helper_writer, ">Previous <span");

WriteLiteralTo(__razor_helper_writer, " class=\"hide-mob\"");

WriteLiteralTo(__razor_helper_writer, ">page</span></span>\r\n                <span");

WriteLiteralTo(__razor_helper_writer, " class=\"counter\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 81 "..\..\Views\Apprenticeship\SearchResults.cshtml"
        WriteTo(__razor_helper_writer, previousPage);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " of ");


#line 81 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                         WriteTo(__razor_helper_writer, Model.LastPage);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span>\r\n            </a>\r\n");


#line 83 "..\..\Views\Apprenticeship\SearchResults.cshtml"
    }


#line default
#line hidden
});

#line 84 "..\..\Views\Apprenticeship\SearchResults.cshtml"
}
#line default
#line hidden

#line 87 "..\..\Views\Apprenticeship\SearchResults.cshtml"
public System.Web.WebPages.HelperResult GetPaginationNextLink()
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 88 "..\..\Views\Apprenticeship\SearchResults.cshtml"
 
    if (Model.ActualPage < Model.LastPage)
    {
        var nextPage = @Model.ActualPage + 1;
        var title = $"Next page {@nextPage} of {@Model.LastPage}";

        //var url = $"Apprenticeship/SearchResults/keywords={Model.SearchTerm}&page={nextPage}";
        var url = @Url.Action("SearchResults", "Apprenticeship", GetNavigationRouteValues(Model.SearchTerm, nextPage, Model.AggregationLevel), null);
            

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "<a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 3318), Tuple.Create("\"", 3329)

#line 96 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 3325), Tuple.Create<System.Object, System.Int32>(url

#line default
#line hidden
, 3325), false)
);

WriteLiteralTo(__razor_helper_writer, " style=\"visibility: visible\"");

WriteLiteralTo(__razor_helper_writer, " class=\"page-navigation__btn next\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <i");

WriteLiteralTo(__razor_helper_writer, " class=\"arrow-button fa fa-angle-right\"");

WriteLiteralTo(__razor_helper_writer, "></i>\r\n                <span");

WriteLiteralTo(__razor_helper_writer, " class=\"description\"");

WriteLiteralTo(__razor_helper_writer, ">Next <span");

WriteLiteralTo(__razor_helper_writer, " class=\"hide-mob\"");

WriteLiteralTo(__razor_helper_writer, ">page</span></span>\r\n                <span");

WriteLiteralTo(__razor_helper_writer, " class=\"counter\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 99 "..\..\Views\Apprenticeship\SearchResults.cshtml"
        WriteTo(__razor_helper_writer, nextPage);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " of ");


#line 99 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                     WriteTo(__razor_helper_writer, Model.LastPage);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span>\r\n            </a>\r\n");


#line 101 "..\..\Views\Apprenticeship\SearchResults.cshtml"
    }


#line default
#line hidden
});

#line 102 "..\..\Views\Apprenticeship\SearchResults.cshtml"
}
#line default
#line hidden

        #line 106 "..\..\Views\Apprenticeship\SearchResults.cshtml"
 
    RouteValueDictionary GetNavigationRouteValues(string keywords, int page, IEnumerable<LevelAggregationViewModel> selectedLevels)
    {

        var rv = new RouteValueDictionary { { "keywords", Model.SearchTerm }, { "page", page } };
        int i = 0;
        foreach (var level in selectedLevels.Where(m => m.Checked))
        {
            rv.Add("SelectedLevels[" + i + "]", level.Value);
            i++;
        }
        return rv;
    }

        #line default
        #line hidden

#line 122 "..\..\Views\Apprenticeship\SearchResults.cshtml"
public System.Web.WebPages.HelperResult GetStandardTitle(ApprenticeshipSearchResultItemViewModel item)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 123 "..\..\Views\Apprenticeship\SearchResults.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <h2");

WriteLiteralTo(__razor_helper_writer, " class=\"result-title\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 125 "..\..\Views\Apprenticeship\SearchResults.cshtml"
WriteTo(__razor_helper_writer, Html.ActionLink(item.Title, "Standard", "Apprenticeship", new { @id = item.StandardId }, null));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " \r\n        <span>new</span>\r\n    </h2>\r\n");


#line 128 "..\..\Views\Apprenticeship\SearchResults.cshtml"


#line default
#line hidden
});

#line 128 "..\..\Views\Apprenticeship\SearchResults.cshtml"
}
#line default
#line hidden

#line 130 "..\..\Views\Apprenticeship\SearchResults.cshtml"
public System.Web.WebPages.HelperResult GetFrameworkTitle(ApprenticeshipSearchResultItemViewModel item)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 131 "..\..\Views\Apprenticeship\SearchResults.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <h2");

WriteLiteralTo(__razor_helper_writer, " class=\"result-title\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 133 "..\..\Views\Apprenticeship\SearchResults.cshtml"
WriteTo(__razor_helper_writer, Html.ActionLink(item.Title, "Framework", "Apprenticeship", new { @id = item.FrameworkId }, null));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n    </h2>\r\n");


#line 135 "..\..\Views\Apprenticeship\SearchResults.cshtml"


#line default
#line hidden
});

#line 135 "..\..\Views\Apprenticeship\SearchResults.cshtml"
}
#line default
#line hidden

#line 137 "..\..\Views\Apprenticeship\SearchResults.cshtml"
public System.Web.WebPages.HelperResult GetApprenticeshipDetailItem(string title, string id, string item, string unit = "")
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 138 "..\..\Views\Apprenticeship\SearchResults.cshtml"
 
    if (!string.IsNullOrEmpty(item))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dt>");


#line 141 "..\..\Views\Apprenticeship\SearchResults.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\r\n");

WriteLiteralTo(__razor_helper_writer, "        <dd");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 4799), Tuple.Create("\"", 4810)

#line 142 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 4807), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 4807), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 142 "..\..\Views\Apprenticeship\SearchResults.cshtml"
WriteTo(__razor_helper_writer, item);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");


#line 142 "..\..\Views\Apprenticeship\SearchResults.cshtml"
WriteTo(__razor_helper_writer, unit);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dd>\r\n");


#line 143 "..\..\Views\Apprenticeship\SearchResults.cshtml"
    }


#line default
#line hidden
});

#line 144 "..\..\Views\Apprenticeship\SearchResults.cshtml"
}
#line default
#line hidden

#line 146 "..\..\Views\Apprenticeship\SearchResults.cshtml"
public System.Web.WebPages.HelperResult FilterForm(string className)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 147 "..\..\Views\Apprenticeship\SearchResults.cshtml"
 
    if (Model.TotalResults > 0)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <div");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 4935), Tuple.Create("\"", 4953)

#line 150 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 4943), Tuple.Create<System.Object, System.Int32>(className

#line default
#line hidden
, 4943), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n            <form");

WriteLiteralTo(__razor_helper_writer, " method=\"get\"");

WriteLiteralTo(__razor_helper_writer, " autocomplete=\"off\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <input");

WriteLiteralTo(__razor_helper_writer, " type=\"hidden\"");

WriteLiteralTo(__razor_helper_writer, " name=\"Keywords\"");

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 5061), Tuple.Create("\"", 5086)

#line 152 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 5069), Tuple.Create<System.Object, System.Int32>(Model.SearchTerm

#line default
#line hidden
, 5069), false)
);

WriteLiteralTo(__razor_helper_writer, " />\r\n                <input");

WriteLiteralTo(__razor_helper_writer, " type=\"hidden\"");

WriteLiteralTo(__razor_helper_writer, " name=\"Page\"");

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 5140), Tuple.Create("\"", 5165)

#line 153 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 5148), Tuple.Create<System.Object, System.Int32>(Model.ActualPage

#line default
#line hidden
, 5148), false)
);

WriteLiteralTo(__razor_helper_writer, " />\r\n                <input");

WriteLiteralTo(__razor_helper_writer, " type=\"hidden\"");

WriteLiteralTo(__razor_helper_writer, " name=\"Keywords\"");

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 5223), Tuple.Create("\"", 5248)

#line 154 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 5231), Tuple.Create<System.Object, System.Int32>(Model.SearchTerm

#line default
#line hidden
, 5231), false)
);

WriteLiteralTo(__razor_helper_writer, " />\r\n\r\n                <fieldset");

WriteLiteralTo(__razor_helper_writer, " class=\"filters filters-accordion\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <h3");

WriteLiteralTo(__razor_helper_writer, " class=\"toggler heading-small\"");

WriteLiteralTo(__razor_helper_writer, ">Apprenticeship Level</h3>\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"toggled-content\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <ul");

WriteLiteralTo(__razor_helper_writer, " name=\"alist22\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 160 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                            

#line default
#line hidden

#line 160 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                             foreach (var item in Model.AggregationLevel.OrderBy(m => m.Value))
                            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                                <li>\r\n                                    <input");

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 5703), Tuple.Create("\"", 5722)

#line 163 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 5711), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 5711), false)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 5723), Tuple.Create("\"", 5754)
, Tuple.Create(Tuple.Create("", 5728), Tuple.Create("SelectedLevels_", 5728), true)

#line 163 "..\..\Views\Apprenticeship\SearchResults.cshtml"
  , Tuple.Create(Tuple.Create("", 5743), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 5743), false)
);

WriteLiteralTo(__razor_helper_writer, " name=\"SelectedLevels\"");

WriteLiteralTo(__razor_helper_writer, " type=\"checkbox\"");

WriteLiteralTo(__razor_helper_writer, " ");


#line 163 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                                                                                                       WriteTo(__razor_helper_writer, Html.Raw(item.Checked ? "checked" : ""));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");


#line 163 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                                                                                                                                                WriteTo(__razor_helper_writer, Html.Raw(item.Count == 0 ? "disabled" : ""));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " />\r\n                                    <label");

WriteAttributeTo(__razor_helper_writer, "for", Tuple.Create(" for=\"", 5926), Tuple.Create("\"", 5958)
, Tuple.Create(Tuple.Create("", 5932), Tuple.Create("SelectedLevels_", 5932), true)

#line 164 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 5947), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 5947), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 5959), Tuple.Create("\"", 6011)

#line 164 "..\..\Views\Apprenticeship\SearchResults.cshtml"
   , Tuple.Create(Tuple.Create("", 5967), Tuple.Create<System.Object, System.Int32>(Html.Raw(item.Count == 0 ? "disabled" : "")

#line default
#line hidden
, 5967), false)
);

WriteLiteralTo(__razor_helper_writer, ">Level ");


#line 164 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                                                                                                         WriteTo(__razor_helper_writer, item.Value);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " (");


#line 164 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                                                                                                                      WriteTo(__razor_helper_writer, item.Count);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ")</label>\r\n                                </li>\r\n");


#line 166 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                        </ul>\r\n\r\n                        <details>\r\n             " +
"               <summary>Help with levels</summary>\r\n                            " +
"<div");

WriteLiteralTo(__razor_helper_writer, " class=\"panel panel-border-narrow\"");

WriteLiteralTo(__razor_helper_writer, @">
                                <p>
                                    What is here?
                                </p>
                            </div>
                        </details>
                    </div>
                </fieldset>
                <input");

WriteLiteralTo(__razor_helper_writer, " type=\"submit\"");

WriteLiteralTo(__razor_helper_writer, " class=\"button\"");

WriteLiteralTo(__razor_helper_writer, " value=\"Update results\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n            </form>\r\n        </div>\r\n");


#line 182 "..\..\Views\Apprenticeship\SearchResults.cshtml"
    }


#line default
#line hidden
});

#line 183 "..\..\Views\Apprenticeship\SearchResults.cshtml"
}
#line default
#line hidden

        public SearchResults()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Apprenticeship\SearchResults.cshtml"
  
    ViewBag.Title = "Search Results";

            
            #line default
            #line hidden
WriteLiteral("\r\n<main");

WriteLiteral(" id=\"content\"");

WriteLiteral(" role=\"main\"");

WriteLiteral(">\r\n    <p");

WriteLiteral(" class=\"small-btm-margin\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\Apprenticeship\SearchResults.cshtml"
   Write(Html.ActionLink("Back", "Search", null, new { @class = "link-back" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n    <div");

WriteLiteral(" id=\"apprenticeship-results\"");

WriteLiteral(" class=\"grid-row column-two-third\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n\r\n            <div>\r\n\r\n                <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">\r\n                    Search results\r\n                </h1>\r\n\r\n            </div" +
">\r\n            <p>\r\n");

            
            #line 22 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                  
                    Html.RenderPartial("_SearchResultMessage");
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Views\Apprenticeship\SearchResults.cshtml"
       Write(FilterForm("filter-mobile"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 29 "..\..\Views\Apprenticeship\SearchResults.cshtml"
            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Apprenticeship\SearchResults.cshtml"
             foreach (var item in Model.Results)
            {

            
            #line default
            #line hidden
WriteLiteral("                <article");

WriteAttribute("class", Tuple.Create(" class=\"", 821), Tuple.Create("\"", 869)
, Tuple.Create(Tuple.Create("", 829), Tuple.Create("result", 829), true)
            
            #line 31 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create(" ", 835), Tuple.Create<System.Object, System.Int32>(item.ApprenticeshipType
            
            #line default
            #line hidden
, 836), false)
, Tuple.Create(Tuple.Create("", 862), Tuple.Create("-result", 862), true)
);

WriteAttribute("id", Tuple.Create(" id=\"", 870), Tuple.Create("\"", 962)
            
            #line 31 "..\..\Views\Apprenticeship\SearchResults.cshtml"
, Tuple.Create(Tuple.Create("", 875), Tuple.Create<System.Object, System.Int32>(item.ApprenticeshipType
            
            #line default
            #line hidden
, 875), false)
, Tuple.Create(Tuple.Create("", 901), Tuple.Create("-", 901), true)
            
            #line 31 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                           , Tuple.Create(Tuple.Create("", 902), Tuple.Create<System.Object, System.Int32>(item.StandardId != 0 ? item.StandardId : item.FrameworkId
            
            #line default
            #line hidden
, 902), false)
);

WriteLiteral(">\r\n                    <header>\r\n");

            
            #line 33 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                         if (item.StandardId != 0)
                        {
                            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                       Write(GetStandardTitle(item));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                                                   
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                       Write(GetFrameworkTitle(item));

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                                                    
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </header>\r\n                    <dl");

WriteLiteral(" class=\"result-data-list\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 43 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                   Write(GetApprenticeshipDetailItem("Level:", "level", item.Level));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 44 "..\..\Views\Apprenticeship\SearchResults.cshtml"
                   Write(GetApprenticeshipDetailItem("Typical length:", "length", item.TypicalLengthMessage));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </dl>\r\n                </article>\r\n");

            
            #line 47 "..\..\Views\Apprenticeship\SearchResults.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"column-one-third\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\Apprenticeship\SearchResults.cshtml"
       Write(FilterForm("filter-desktop"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"page-navigation\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 56 "..\..\Views\Apprenticeship\SearchResults.cshtml"
       Write(GetPaginationBackLink());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 57 "..\..\Views\Apprenticeship\SearchResults.cshtml"
       Write(GetPaginationNextLink());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div> \r\n    </div>\r\n</main>\r\n\r\n");

            
            #line 62 "..\..\Views\Apprenticeship\SearchResults.cshtml"
 if (Model.TotalResults == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n        window.onload = function() {\r\n            SearchAndShortlis" +
"t.analytics.pushEvent(\"Apprenticeship Search\", \"No results\", \"Search\");\r\n       " +
" }\r\n    </script>\r\n");

            
            #line 69 "..\..\Views\Apprenticeship\SearchResults.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
