#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfa.Das.Sas.Web.Views.Apprenticeship
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Apprenticeship\Standard.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Apprenticeship\Standard.cshtml"
    using Sfa.Das.Sas.Resources;
    
    #line default
    #line hidden
    using Sfa.Das.Sas.Web;
    
    #line 3 "..\..\Views\Apprenticeship\Standard.cshtml"
    using Sfa.Das.Sas.Web.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Apprenticeship/Standard.cshtml")]
    public partial class Standard : System.Web.Mvc.WebViewPage<Sfa.Das.Sas.Web.ViewModels.StandardViewModel>
    {

#line 115 "..\..\Views\Apprenticeship\Standard.cshtml"
public System.Web.WebPages.HelperResult GetStandardProperty(string title, string id, string item, bool hideIfEmpty = false)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 116 "..\..\Views\Apprenticeship\Standard.cshtml"
 
    if (!string.IsNullOrEmpty(item) || !hideIfEmpty)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dt>");


#line 119 "..\..\Views\Apprenticeship\Standard.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\r\n");

WriteLiteralTo(__razor_helper_writer, "        <dd");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 6006), Tuple.Create("\"", 6014)

#line 120 "..\..\Views\Apprenticeship\Standard.cshtml"
, Tuple.Create(Tuple.Create("", 6011), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 6011), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 120 "..\..\Views\Apprenticeship\Standard.cshtml"
WriteTo(__razor_helper_writer, Html.MarkdownToHtml(item));


#line default
#line hidden

#line 120 "..\..\Views\Apprenticeship\Standard.cshtml"
                                                if (item == null){ 

#line default
#line hidden

#line 120 "..\..\Views\Apprenticeship\Standard.cshtml"
                                     WriteTo(__razor_helper_writer, Html.Raw("&nbsp;"));


#line default
#line hidden

#line 120 "..\..\Views\Apprenticeship\Standard.cshtml"
                                                                                       }

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dd>\r\n");


#line 121 "..\..\Views\Apprenticeship\Standard.cshtml"
    }


#line default
#line hidden
});

#line 122 "..\..\Views\Apprenticeship\Standard.cshtml"
}
#line default
#line hidden

#line 124 "..\..\Views\Apprenticeship\Standard.cshtml"
public System.Web.WebPages.HelperResult GetDurationProperty(string title, string id, string item, bool hideIfEmpty = false)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 125 "..\..\Views\Apprenticeship\Standard.cshtml"
 
    if (!string.IsNullOrEmpty(item) || !hideIfEmpty)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dt>");


#line 128 "..\..\Views\Apprenticeship\Standard.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\r\n");

WriteLiteralTo(__razor_helper_writer, "        <dd");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 6295), Tuple.Create("\"", 6303)

#line 129 "..\..\Views\Apprenticeship\Standard.cshtml"
, Tuple.Create(Tuple.Create("", 6300), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 6300), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 129 "..\..\Views\Apprenticeship\Standard.cshtml"
WriteTo(__razor_helper_writer, item);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " months</dd>\r\n");


#line 130 "..\..\Views\Apprenticeship\Standard.cshtml"
    }


#line default
#line hidden
});

#line 131 "..\..\Views\Apprenticeship\Standard.cshtml"
}
#line default
#line hidden

#line 133 "..\..\Views\Apprenticeship\Standard.cshtml"
public System.Web.WebPages.HelperResult GetFundingBandProperty(int value)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 134 "..\..\Views\Apprenticeship\Standard.cshtml"
 
    var fundingCapFormatted = value.ToString("C0", new CultureInfo("en-GB"));



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <dt>Current funding band</dt>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <dd");

WriteLiteralTo(__razor_helper_writer, " id=\"funding-cap\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        Up to ");


#line 139 "..\..\Views\Apprenticeship\Standard.cshtml"
WriteTo(__razor_helper_writer, fundingCapFormatted);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " per apprentice.<br />\r\n        <a");

WriteLiteralTo(__razor_helper_writer, " href=\"https://www.gov.uk/guidance/employing-an-apprentice-technical-guide-for-em" +
"ployers#funding-for-your-apprenticeship\"");

WriteLiteralTo(__razor_helper_writer, " target=\"_blank\"");

WriteLiteralTo(__razor_helper_writer, " rel=\"external\"");

WriteLiteralTo(__razor_helper_writer, ">More information about funding</a>\r\n    </dd>\r\n");


#line 142 "..\..\Views\Apprenticeship\Standard.cshtml"


#line default
#line hidden
});

#line 142 "..\..\Views\Apprenticeship\Standard.cshtml"
}
#line default
#line hidden

#line 144 "..\..\Views\Apprenticeship\Standard.cshtml"
public System.Web.WebPages.HelperResult GetDocumentItem(string pdfUrl, string title)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 145 "..\..\Views\Apprenticeship\Standard.cshtml"
 
    if (!string.IsNullOrEmpty(title))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <li>\r\n            <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 6929), Tuple.Create("\"", 6943)

#line 149 "..\..\Views\Apprenticeship\Standard.cshtml"
, Tuple.Create(Tuple.Create("", 6936), Tuple.Create<System.Object, System.Int32>(pdfUrl

#line default
#line hidden
, 6936), false)
);

WriteLiteralTo(__razor_helper_writer, " target=\"_blank\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 150 "..\..\Views\Apprenticeship\Standard.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </a>\r\n        </li>\r\n");


#line 153 "..\..\Views\Apprenticeship\Standard.cshtml"
    }


#line default
#line hidden
});

#line 154 "..\..\Views\Apprenticeship\Standard.cshtml"
}
#line default
#line hidden

        public Standard()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Apprenticeship\Standard.cshtml"
  
    ViewBag.Title = Model.Title + " - Apprenticeship Standard";
    ViewBag.Description = Model.OverviewOfRole;
    var areOrganisationsPresent = Model.AssessmentOrganisations != null && Model.AssessmentOrganisations.Any();


            
            #line default
            #line hidden
WriteLiteral("\r\n<main");

WriteLiteral(" id=\"content\"");

WriteLiteral(" class=\"standard-detail\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n            <div>\r\n                <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 16 "..\..\Views\Apprenticeship\Standard.cshtml"
               Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </h1>\r\n                <p>");

            
            #line 18 "..\..\Views\Apprenticeship\Standard.cshtml"
              Write(Model.OverviewOfRole);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"hidden-for-mobile-tablet\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"button btn-find-trng-prov\"");

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(" id=\"ga-find-provider-top\"");

WriteAttribute("href", Tuple.Create(" href=\"", 829), Tuple.Create("\"", 963)
            
            #line 21 "..\..\Views\Apprenticeship\Standard.cshtml"
                     , Tuple.Create(Tuple.Create("", 836), Tuple.Create<System.Object, System.Int32>(Url.Action("SearchForStandardProviders", "Apprenticeship", new { standardId = Model.StandardId, keywords = Model.SearchTerm })
            
            #line default
            #line hidden
, 836), false)
);

WriteLiteral(">\r\n                    Find training providers\r\n                </a>\r\n           " +
" </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"column-third\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"related-container\"");

WriteLiteral(">\r\n                \r\n            </div>\r\n        </div>\r\n    </div>\r\n    <section" +
">\r\n        <header>\r\n            <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">\r\n                Summary of this apprenticeship standard\r\n            </h2>\r\n  " +
"      </header>\r\n        <dl");

WriteLiteral(" class=\"data-list\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 39 "..\..\Views\Apprenticeship\Standard.cshtml"
       Write(GetStandardProperty("Level", "level", $"{@Model.Level} (equivalent to {EquivalenceLevelService.GetApprenticeshipLevel(Model.Level.ToString())})"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 40 "..\..\Views\Apprenticeship\Standard.cshtml"
       Write(GetDurationProperty("Typical length", "length", Model.Duration.ToString()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 41 "..\..\Views\Apprenticeship\Standard.cshtml"
       Write(GetFundingBandProperty(Model.MaxFunding));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 42 "..\..\Views\Apprenticeship\Standard.cshtml"
       Write(GetStandardProperty("Entry requirements", "entry-requirements", Model.EntryRequirements));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Views\Apprenticeship\Standard.cshtml"
       Write(GetStandardProperty("What apprentices will learn", "will-learn", Model.WhatApprenticesWillLearn));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Views\Apprenticeship\Standard.cshtml"
       Write(GetStandardProperty("Qualifications", "qualifications", Model.Qualifications));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Apprenticeship\Standard.cshtml"
       Write(GetStandardProperty("Professional registration", "professional-registration", Model.ProfessionalRegistration, true));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <dt>Documents</dt>\r\n            <dd>\r\n                <div");

WriteLiteral(" class=\"panel-indent panel-indent-info document-list\"");

WriteLiteral(">\r\n                    <ul>\r\n");

WriteLiteral("                        ");

            
            #line 50 "..\..\Views\Apprenticeship\Standard.cshtml"
                   Write(GetDocumentItem(Model.StandardPdf, "Standard"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 51 "..\..\Views\Apprenticeship\Standard.cshtml"
                   Write(GetDocumentItem(Model.AssessmentPlanPdf, "Assessment Plan"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </ul>\r\n                </div>\r\n            </dd>\r\n");

            
            #line 55 "..\..\Views\Apprenticeship\Standard.cshtml"
            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Apprenticeship\Standard.cshtml"
             if (areOrganisationsPresent == false)
            {
                const string noDetails = @"There are no end point assessment organisations for this standard yet. There is a monthly application process for organisations interested in delivering end-point assessment. " + 
                                            "New organisations are added regularly.<br /><br />If you have an urgent need to select an assessment organisation for this standard, " +
                                            "please email <a href='mailto:apprentice.assessment@education.gov.uk' target='_blank'>apprentice.assessment@education.gov.uk</a> with details.";
                
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Apprenticeship\Standard.cshtml"
           Write(GetStandardProperty("End Point Assessment", "no-assessment-organisations", noDetails));

            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Apprenticeship\Standard.cshtml"
                                                                                                      
           
            }

            
            #line default
            #line hidden
WriteLiteral("</dl>\r\n");

            
            #line 64 "..\..\Views\Apprenticeship\Standard.cshtml"
        
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Apprenticeship\Standard.cshtml"
         if (areOrganisationsPresent)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"column-full\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"collapsible\"");

WriteLiteral(">End Point Assessment </p>\r\n\r\n                <details>\r\n\r\n                    <s" +
"ummary><span");

WriteLiteral(" class=\"summary\"");

WriteLiteral(" style=\"text-decoration: none\"");

WriteLiteral(">View a list of end point assessment organisations for this standard</span></summ" +
"ary>\r\n\r\n                    <table");

WriteLiteral(" class=\"responsive\"");

WriteLiteral(">\r\n                        <thead>\r\n                        <tr>\r\n               " +
"             <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Organisation</th>\r\n                            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Phone Number</th>\r\n                            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Email</th>\r\n                        </tr>\r\n                        </thead>\r\n   " +
"                     <tbody>\r\n");

            
            #line 83 "..\..\Views\Apprenticeship\Standard.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Apprenticeship\Standard.cshtml"
                         foreach (var organisation in Model.AssessmentOrganisations)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td");

WriteLiteral(" class=\"organisation-name\"");

WriteLiteral(" data-label=\"organisation\"");

WriteLiteral(">\r\n");

            
            #line 87 "..\..\Views\Apprenticeship\Standard.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\Apprenticeship\Standard.cshtml"
                                     if (string.IsNullOrEmpty(organisation.Website))
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Apprenticeship\Standard.cshtml"
                                   Write(organisation.Name);

            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Apprenticeship\Standard.cshtml"
                                                          
                                    }
                                    else
                                    {
                                        var linkProtocol = organisation.Website.StartsWith("http") ? string.Empty : "http://";


            
            #line default
            #line hidden
WriteLiteral("                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4829), Tuple.Create("\"", 4870)
            
            #line 95 "..\..\Views\Apprenticeship\Standard.cshtml"
, Tuple.Create(Tuple.Create("", 4836), Tuple.Create<System.Object, System.Int32>(linkProtocol
            
            #line default
            #line hidden
, 4836), false)
            
            #line 95 "..\..\Views\Apprenticeship\Standard.cshtml"
, Tuple.Create(Tuple.Create("", 4849), Tuple.Create<System.Object, System.Int32>(organisation.Website
            
            #line default
            #line hidden
, 4849), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 95 "..\..\Views\Apprenticeship\Standard.cshtml"
                                                                                                Write(organisation.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 96 "..\..\Views\Apprenticeship\Standard.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                                <td");

WriteLiteral(" class=\"phone-number\"");

WriteLiteral(" data-label=\"phone-number\"");

WriteLiteral(">");

            
            #line 98 "..\..\Views\Apprenticeship\Standard.cshtml"
                                                                              Write(organisation.Phone);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td");

WriteLiteral(" class=\"email\"");

WriteLiteral(" data-label=\"email\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5170), Tuple.Create("\"", 5203)
, Tuple.Create(Tuple.Create("", 5177), Tuple.Create("mailto:", 5177), true)
            
            #line 99 "..\..\Views\Apprenticeship\Standard.cshtml"
     , Tuple.Create(Tuple.Create("", 5184), Tuple.Create<System.Object, System.Int32>(organisation.Email
            
            #line default
            #line hidden
, 5184), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 99 "..\..\Views\Apprenticeship\Standard.cshtml"
                                                                                                                     Write(organisation.Email);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                            </tr>\r\n");

            
            #line 101 "..\..\Views\Apprenticeship\Standard.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/details>\r\n            </div>\r\n        </div>\r\n");

            
            #line 107 "..\..\Views\Apprenticeship\Standard.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"bottom-actions\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"button btn-find-trng-prov\"");

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(" id=\"ga-find-provider-bottom\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5575), Tuple.Create("\"", 5709)
            
            #line 109 "..\..\Views\Apprenticeship\Standard.cshtml"
                   , Tuple.Create(Tuple.Create("", 5582), Tuple.Create<System.Object, System.Int32>(Url.Action("SearchForStandardProviders", "Apprenticeship", new { standardId = Model.StandardId, keywords = Model.SearchTerm })
            
            #line default
            #line hidden
, 5582), false)
);

WriteLiteral(">\r\n                Find training providers\r\n            </a>\r\n        </div>\r\n   " +
" </section>\r\n</main>\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
